language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t davideberno/react-todo -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davideberno/react-todo npm run test

after_success:
  - docker build -t davideberno/react-todo-client ./client
  - docker build -t davideberno/react-todo-nginx ./nginx
  - docker build -t davideberno/react-todo-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push davideberno/react-todo-client
  - docker push davideberno/react-todo-nginx
  - docker push davideberno/react-todo-server

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "react-todo"
  env: "ReactTodo-env"
  bucket_name: "elasticbeanstalk-eu-central-1-174559844437"
  bucket_path: "react-todo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
