language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t davideberno/react-todo -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davideberno/react-todo npm run test
