version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    # ports:
    #   - 8080:8080
  # mongo:
  #   image: mongo:latest
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    # ports:
    #   - 3000:3000
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
